= Quicksort/Quickselect with median of medians

== About
This is an implementation of Quicksort and Quickselect[1].

Instead of the introspection technique[2,3], this implementation uses 
(a variant of) the median of medians[4] to ensure that the worst case 
runtimes of the routines are Θ(N ln N) and Θ(N), respectively.

This program is under the CC0 and without any warranty.

1. C.A.R. Hoare, Commun. ACM 4, 321 (1961).
2. 野崎昭弘, 杉本俊彦, 情報処理学会論文誌 21, 164 (1980).
3. D.R. Musser, Software Pract. Exper. 27, 983 (1997).
4. M. Blum, et al., J. Comput. Syst. Sci. 7, 448 (1973).


== Benchmark

We sort random sequence of one million (10 million) distinct 32bits-integers 100-times and measure the comparison count and running time of quicksort(quickselect).
We can see that our implementations are as efficient as the library routines of daily use.


.Benchmark Environment
|===========================================
| CPU              | AMD A4-5300 APU
| RAM              | 8 GiB
| OS               | FreeBSD 11.0-RELEASE-p2
| Compiler         | clang 3.8.0
| Compiler Options | -O3 -DNDEBUG
|===========================================



.Quicksort Result
[options="header"]
|===========================================================
|                  | Comparison         | Time [s]
| std::sort        | 2.18(2)   x 10^7^  | 0.132(2)
| our C++ version  | 2.0551(6) x 10^7^  | 0.094(1)
| qsort            | 2.09(2)   x 10^7^  | 0.202(4)
| our C version    | 1.9987(6) x 10^7^  | 0.181(3)
|===========================================================


.Quickselect Result
[options="header"]
|===========================================================
|                  | Comparison         | Time [s]
| std::nth_element | 2.8(5)  x 10^7^    | 0.085(9) 
| our C++ version  | 2.81(2) x 10^7^    | 0.117(2) 
| (not in libc)    | N/A                | N/A
| our C version    | 2.81(2) x 10^7^    | 0.233(4)
|===========================================================



== How to use

=== C
The main routines have the following prototypes:
--------
void quicksort_mm_quicksort(
    void *p, size_t nelem, size_t size, 
    int (*cmp)(const void *, const void *)
);

void quicksort_mm_quickselect(
    void *p, size_t nelem, size_t size, 
    size_t kth, 
    int (*cmp)(const void *, const void *)
);
--------

The function +quicksort_mm_quickselect+ modifies the input array,
 and set the k-th element to the k-th position. 


=== C++
This is header only library (+src/cc/quicksort_mm.hh+).
The main routines have the following prototypes:

--------
template<class RandomAccessIterator>
void quicksort_mm::quicksort(
    RandomAccessIterator first, 
    RandomAccessIterator last
);

template<class RandomAccessIterator, class Compare>
void quicksort_mm::quicksort(
    RandomAccessIterator first, 
    RandomAccessIterator last,
    Compare cmp
);


template<class RandomAccessIterator>
void quicksort_mm::quickselect(
    RandomAccessIterator first,
    RandomAccessIterator kth,
    RandomAccessIterator last
);

template<class RandomAccessIterator, class Compare>
void quicksort_mm::quickselect(
    RandomAccessIterator first,
    RandomAccessIterator kth,
    RandomAccessIterator last,
    Compare cmp
);
--------

The aboves are the same as std::sort and std::nth_element.
